namenode:
  image: uhopper/hadoop-namenode
  hostname: namenode
  container_name: namenode
  domainname: hadoop
  net: hadoop
  volumes:
    - namenode:/hadoop/dfs/name
  environment:
    - CLUSTER_NAME=test
  env_file:
    - ./hadoop.env

resourcemanager:
  image: uhopper/hadoop-resourcemanager
  hostname: resourcemanager
  container_name: resourcemanager
  domainname: hadoop
  net: hadoop
  env_file:
    - ./hadoop.env

historyserver:
  image: uhopper/hadoop-historyserver
  hostname: historyserver
  container_name: historyserver
  domainname: hadoop
  net: hadoop
  volumes:
    - historyserver:/hadoop/yarn/timeline
  env_file:
    - ./hadoop.env

spark:
  image: uhopper/hadoop-spark
  hostname: spark
  container_name: spark
  domainname: hadoop
  net: hadoop
  environment:
    - SPARK_CONF_spark_eventLog_enabled=true
    - SPARK_CONF_spark_eventLog_dir=hdfs://namenode:8020/spark-logs
    - SPARK_CONF_spark_history_fs_logDirectory=hdfs://namenode:8020/spark-logs
  env_file:
    - ./hadoop.env

spark-notebook:
  image: uhopper/hadoop-spark-notebook
  hostname: sparknotebook
  container_name: sparknotebook
  domainname: hadoop
  net: hadoop
  environment:
    - SPARK_NOTEBOOK_MASTER=yarn-client  
  env_file:
    - ./hadoop.env    

nodemanager1:
  image: uhopper/hadoop-nodemanager
  hostname: nodemanager1
  container_name: nodemanager1
  domainname: hadoop
  net: hadoop
  env_file:
    - ./hadoop.env

datanode1:
  image: uhopper/hadoop-datanode
  hostname: datanode1
  container_name: datanode1
  domainname: hadoop
  net: hadoop
  volumes:
    - datanode1:/hadoop/dfs/data
  env_file:
    - ./hadoop.env

datanode2:
  image: uhopper/hadoop-datanode
  hostname: datanode2
  container_name: datanode2
  domainname: hadoop
  net: hadoop
  volumes:
    - datanode2:/hadoop/dfs/data
  env_file:
    - ./hadoop.env